eureka:
  client:
    service-url:
      defaultZone: http://localhost:9091/eureka/,http://localhost:9091/eureka/
product-service:
  ribbon:
    #NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 0 # 切换实例的重试次数
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'

spring:
  rabbitmq:
    host: 134.175.100.149
    port: 5672
    username: zs
    password: 123
    virtual-host: /OFzs
    
    
image:
  server: 123123456456
